--- 
jobs: 
  include: 
    - 
      before_install: 
        - "wget https://saw.galois.com/builds/nightly/saw-0.4.0.99-2020-04-24-OSX-64.tar.gz"
        - "tar -xzf saw-0.4.0.99-2020-04-24-OSX-64.tar.gz"
        - "export PATH=$PATH:saw-0.4.0.99-2020-04-24-OSX-64/bin"
        - saw --version
        - "wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.7/z3-4.8.7-x64-osx-10.14.6.zip"
        - "unzip z3-4.8.7-x64-osx-10.14.6.zip"
        - "export PATH=$PATH:z3-4.8.7-x64-osx-10.14.6/bin"
        - z3 --version
        - "brew install SRI-CSL/sri-csl/yices2"
        - yices-smt2 --version
      compiler: clang
      os: osx
    - 
      before_install: 
        - "wget https://saw.galois.com/builds/nightly/saw-0.4.0.99-2020-04-24-Ubuntu14.04-64.tar.gz"
        - "tar -xzf saw-0.4.0.99-2020-04-24-Ubuntu14.04-64.tar.gz"
        - "export PATH=$PATH:saw-0.4.0.99-2020-04-24-Ubuntu14.04-64/bin"
        - saw --version
        - "wget https://github.com/Z3Prover/z3/archive/z3-4.8.7.tar.gz"
        - "tar -xvzf z3-4.8.7.tar.gz"
        - "(cd z3-z3-4.8.7 && make && sudo make install)"
        - z3 --version
        - "sudo add-apt-repository -y ppa:sri-csl/formal-methods"
        - "sudo apt-get update"
        - "sudo apt-get install -y yices2"
        - yices-smt2 --version
      compiler: clang
      dist: bionic
      os: linux
language: c
script: 
  - make
  - "make test/test"
  - test/test
  - "make saw"
