language: c

jobs: 
  include: 
    - compiler: clang
      os: osx
      before_install: 
        - "wget https://saw.galois.com/builds/nightly/saw-0.4.0.99-2020-04-23-OSX-64.tar.gz"
        - "tar -xzf saw-0.4.0.99-2020-04-23-OSX-64.tar.gz"
        - "export PATH=$PATH:saw-0.4.0.99-2020-04-23-OSX-64/bin"
        - "brew install z3"
        - "brew install SRI-CSL/sri-csl/yices2"
      script: 
        - make
        - "make test/test"
        - test/test
        - "make saw"

#  - os: linux
#    dist: bionic
