--- 
jobs: 
  include: 
    - 
      before_install: 
        - "wget https://saw.galois.com/builds/nightly/saw-0.4.0.99-2020-04-24-OSX-64.tar.gz"
        - "tar -xzf saw-0.4.0.99-2020-04-24-OSX-64.tar.gz"
        - "export PATH=$PATH:saw-0.4.0.99-2020-04-24-OSX-64/bin"
        - "brew install z3"
        - "brew install SRI-CSL/sri-csl/yices2"
      compiler: clang
      os: osx
    - 
      before_install: 
        - "wget https://saw.galois.com/builds/nightly/saw-0.4.0.99-2020-04-24-Ubuntu14.04-64.tar.gz"
        - "tar -xzf saw-0.4.0.99-2020-04-24-Ubuntu14.04-64.tar.gz"
        - "export PATH=$PATH:saw-0.4.0.99-2020-04-24-Ubuntu14.04-64/bin"
        - "sudo apt-get install -y z3"
        - "sudo add-apt-repository -y ppa:sri-csl/formal-methods"
        - "sudo apt-get update"
        - "sudo apt-get install -y yices2"
      compiler: clang
      dist: bionic
      os: linux
language: c
script: 
  - make
  - "make test/test"
  - test/test
  - "make saw"
